### ISSUE TITLE
Minor feedback

### ISSUE THREAD

**Issue by jdom** [OrleansContrib/Orleans.Clustering.Kubernetes#1]
Good stuff, dude! This will be extremely useful.
I've noticed that the options class is in the `Orleans.Clustering.Kubernetes.Options` namespace... I would just drop the Options sub-namespace, as this is one of the main surface APIs for the end-user.

Also no need to annotate it with Json attributes at all, since you are not deviating from the defaults anyway.

**Comment by galvesribeiro** [comment]
Thanks for the feedback man! Will change that. More will come tonight!

Thanks

**Comment by SebastianStehle** [comment]
I think for the extended protocol you have to write the version and the membership info in one transaction. For MongoDB we just dropped this.

**Comment by galvesribeiro** [comment]
@SebastianStehle it is the _ideal_ but not required if transactions is not available. The timestamp will change so no body will be able (at least not in practical time) to write to it.

The extended does nothing more than sort/group the records by clusterVersion. 

If it comes to be a problem here, I'll drop it as well. 

Thanks for the feedback.

**Comment by galvesribeiro** [comment]
First package and samples are out. The changes suggested were added. 

Please keep up with the feedback.

Thanks!
