### ISSUE TITLE
ClusterId in KubeGatewayListProvider not used for Silo CRD filtering

### ISSUE THREAD

**Issue by applicativex** [OrleansContrib/Orleans.Clustering.Kubernetes#14]
ClusterId in https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes/blob/fd688abe427de9962fb3a0c05da47898f077b4be/src/Orleans.Clustering.Kubernetes/KubeGatewayListProvider.cs is used just for logging. Those silos from seperate clusters trying to join other clusters. Is this expected behavior?

**Comment by galvesribeiro** [comment]
The reason it wasn't filtering, is that it was assumed that a single cluster would be deployed per kube namespace. 

Do you think it is not reasonable way to deploy it? In which situation you think multiple clusters would be deploy to the same namespace.

It can easily be changed but I would like to understand the real usecases for it.

Thanks

**Comment by applicativex** [comment]
In our case we are considering k8s namespace as environment in which will be hosted multiple services

**Comment by galvesribeiro** [comment]
Hey @applicativex sorry for the delay.

The fix for this is out. Please update your nuget package to 1.0.19.

I'm closing the issue but feel free to re-open or create another one if you have any issues.

Thank you for the feedback!
