### ISSUE TITLE
KubeMembershipTable Error:  Initial ClusterVersionEntity entity doesn't exist.

### ISSUE THREAD

**Issue by jrouaix** [OrleansContrib/Orleans.Clustering.Kubernetes#17]
Hello there,

I am testing the Kubernetes clustering on a minikube on windows 10.
RBAC is activated, and i deployer the CRDs : 
![image](https://user-images.githubusercontent.com/2705498/50827401-a3e36680-133e-11e9-99ae-d28c4f1dbce0.png)

Then I gave INSANE privileges to my pods :
![image](https://user-images.githubusercontent.com/2705498/50827467-d1301480-133e-11e9-91b0-ef569bba8f51.png)

And then I have this error :
![image](https://user-images.githubusercontent.com/2705498/50827506-e6a53e80-133e-11e9-87c7-bd506126eb9d.png)

The Silo won't start :-(

Any idea ?

**Comment by GabbySF** [comment]
I am having a similar issue did you figure out a solution?

**Comment by jrouaix** [comment]
Nope, backedoff to the SQL Server clustering. I have to test on a non RBAC enabled cluster but I didn't success at disable RBAC on minikube.

Also I wonder about using a kubernetes services (with  ClusterIP:None) and use the DNS lookup as silo discovery ... but it lacks the possibility to declare suspect & dead silos clearly

**Comment by galvesribeiro** [comment]
Sorry for taking that long to reply...

So, it looks to me that you are using `Orleans` as your group. That doesn't work. The error is not related to the `ClusterVersionEntity`. 

Look at the first message. It must be a lower-case DNS name. This is not a problem with the provider. It is how kubernetes works.

Can you paste your silo configuration here?

**Comment by jrouaix** [comment]
Ho you're right, my ClusterId was "Orleans"
![image](https://user-images.githubusercontent.com/2705498/51319517-983e2100-1a5d-11e9-9c02-371d3586162c.png)
I just added the ToLower() part of the configuration.
I'll let you know when I'll try like that.

**Comment by lfzm** [comment]
@jrouaix I also encountered this problem, can I do the corresponding processing with Orleans.Clustering.Kubernetes,

**Comment by jrouaix** [comment]
Hi @lfzm, I finally didn't try again the Kubernetes clustering but I'm confident @galvesribeiro gave me the right tip. For now we moved to another actor model framework, I won't try again soon.
