### ISSUE TITLE
ISiloBuilder and Orleans 2.3.0 HostBuilder Extensions

### ISSUE THREAD

**Issue by mthird** [OrleansContrib/Orleans.Clustering.Kubernetes#22]
I upgraded to the latest Orleans 2.3.0 build today in hopes of using the new ```HostBuilder``` extensions.   However, I noticed the ```HostBuilder.UseOrleans``` method expects an action with a parameter of ```ISiloBuilder``` instead of ```ISiloHostBuilder``` that Orleans.Clustering expects.

The change to support this looks to be a straightforward addition to the extensions class where the ```this``` parameter is of ```ISiloBuilder``` type.

```c#
        public static ISiloBuilder UseKubeMembership(this ISiloBuilder builder,
            Action<KubeClusteringOptions> configureOptions)
        {
            return builder.ConfigureServices(services => services.UseKubeMembership(configureOptions));
        }
```

**Comment by mthird** [comment]
After testing this out, it isn't as simple as adding those method signatures.   There is an issue that I think points to having multiple containers running:

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: address
at System.Net.IPEndPoint..ctor(IPAddress address, Int32 port)
at Orleans.Hosting.EndpointOptionsExtensions.GetPublicSiloEndpoint(EndpointOptions options)
at Orleans.Runtime.LocalSiloDetails.<>c__DisplayClass2_0.<.ctor>b__0()
at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
at System.Lazy`1.CreateValue()
at Orleans.Runtime.Silo..ctor(ILocalSiloDetails siloDetails, IServiceProvider services)
```

**Comment by ReubenBond** [comment]
@mthird how are the `EndpointOptions` configured?

**Comment by mthird** [comment]
```c#
        b.UseKubeMembership(opt =>
        {
             opt.CanCreateResources = false;
             opt.DropResourcesOnInit = false;
        })
        .Configure<EndpointOptions>(options => options.AdvertisedIPAddress = IPAddress.Any);
```

I also tried moving the ```EndpointOptions``` before ```UseKubeMembership```, but get the following error:

```Unhandled Exception: Orleans.Runtime.OrleansConfigurationException: Invalid value specified for AdvertisedIPAddress. The value was 0.0.0.0```

It's highly likely I'm doing something wrong, but a clue is that this setup works correctly using the regular ```SiloHostBuilder```.

**Comment by ReubenBond** [comment]
@mthird `AdvertisedIPAddress` should not be set to `IPAddress.Any` - that property is what other silos use to contact this silo, so setting it to 0.0.0.0 won't work.

Set the listening addresses to Any and leave the advertised address unset. Also set the ports.

**Comment by mthird** [comment]
Odd, none of the endpoint options were necessary using the ```SiloHostBuilder```.

In any case, here is my solution:
```c#
    .Configure<EndpointOptions>(options =>
    {
        var podIp = Environment.GetEnvironmentVariable("POD_IP");
        if (String.IsNullOrEmpty(podIp))
        {
            throw new Exception("Could not find POD_IP environment variable");
        }
        var listen = IPAddress.Parse(podIp);
        options.SiloListeningEndpoint = new IPEndPoint(listen, 10000);
        options.GatewayListeningEndpoint = new IPEndPoint(listen, 30000);
        options.AdvertisedIPAddress = listen;
    })
    .UseKubeMembership(opt =>
    {
        opt.CanCreateResources = false;
        opt.DropResourcesOnInit = false;
    });
```

Then use the downward api in the deployment manifest to get the pod IP:
```yaml
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
```

**Comment by mthird** [comment]
While moving the code over, I forgot to include *the* key piece:

```c#
.ConfigureEndpoints(10000, 30000, listenOnAnyHostAddress: true)
```
Thanks for your patience and for this great library.
