### ISSUE TITLE
Feature request: allow field selector on status

### ISSUE THREAD

**Issue by rmja** [OrleansContrib/Orleans.Clustering.Kubernetes#25]
For housekeeping it would be neat if one could write:

```
kubectl get silos --all-namespaces --field-selector "status=dead"
```

But this currently returns the error `Error from server (BadRequest): Unable to find "silos" that match label selector "", field selector "status=dead": field label not supported: status`

See more here: https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/

**Comment by galvesribeiro** [comment]
Idk if this still relevant. The latest version 1.1.1 already implement the cleanup of dead silos. Please re-open if you still believe we should have that. 

Thank you!
