### ISSUE TITLE
Orleans v7

### ISSUE THREAD

**Issue by tomhreb** [OrleansContrib/Orleans.Clustering.Kubernetes#59]
Hi, is there any plan to add support for .net 7 (Orleans v7)? 

I could start working on it as well.

Tomas

**Comment by SamEmber** [comment]
Hey,

I also need Orleans 7 support, happy to contribute if we can get the go ahead?

Thanks,

Sam

**Comment by SamEmber** [comment]
I have done the work here:

https://github.com/OrleansContrib/Orleans.Clustering.Kubernetes/pull/60

:)

**Comment by PaskeS** [comment]
Amazing work @SamEmber 
We are looking to move to Orleans 7 for our new projects to avoid difficult migrations
Would love to see this go in soon

**Comment by rsirny** [comment]
@galvesribeiro I see you approved the last PR, could you weigh in on what the next steps should be? Is the repo still under your curation?

Thanks!

**Comment by galvesribeiro** [comment]
Hello!

I've made a comment on the PR. As soon as it is fixed I'll merge/release v7.0.0.

Thanks!

**Comment by PaskeS** [comment]
Push action on the package looks to have failed if we can look into that please
