### ISSUE TITLE
Implement sidecar support

### ISSUE THREAD

**Issue by galvesribeiro** [OrleansContrib/Orleans.Clustering.Kubernetes#6]
In kubernetes there is a pattern for Sidecard containers. They essentially live in the same `pod` as the main container. 

A valid use case for sidecar containers in Orleans context, is that you may want to use the main container as a ASP.Net Core container which expose a WebAPI and have a sidecar container which is the silo. As kubernetes runtime thinks that a `pod` is alive and healthy only if _all_ containers within that `pod` are alive, in this particular case, the WebAPI has a guarantee that the silo it is talking is alive. 

With this feature, I would like to be able to configure the gateway list provider to instead of querying the Kube API for the list of silos, to always think it has a single gateway, which is on `localhost` as all container in the same `pod` share the same networking namespace. 

That would avoid the need to call Kube API and hence all the configuration necessary to do so from the client side, leaving that for the silo/sidecar container.

**Comment by aprooks** [comment]
Is it relevant, considering local client is now released?

**Comment by galvesribeiro** [comment]
@aprooks 

Yes, it is not relevant anymore. I'm closing it. Thanks!
