### ISSUE TITLE
Orleans 8.2.0

### ISSUE THREAD

**Issue by turowicz** [OrleansContrib/Orleans.Clustering.Kubernetes#76]
Please upgrade to Orleans 8.2.0 :)

cc @galvesribeiro cc @vader1986

**Comment by galvesribeiro** [comment]
Hello! 

https://www.nuget.org/packages/Orleans.Clustering.Kubernetes/8.2.0

Updated version pushed. Should be available on NuGet soon.

Thanks!

**Comment by turowicz** [comment]
Thank you so much!
